
-- Create devicetypes table
CREATE TABLE "VtDevice".devicetypes (
	devicetypeid int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	typename text NOT NULL,
	description text NOT NULL,
	issensor bool NOT NULL,
	iscontroller bool NOT NULL,
	CONSTRAINT pk_devicetypes PRIMARY KEY (devicetypeid)
);

-- Create devicetemplates table
CREATE TABLE "VtDevice".devicetemplates (
	devicetemplateid int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" text NOT NULL,
	model text NOT NULL,
	description text NOT NULL,
	image bytea NULL,
	devicetypeid int4 NOT NULL,
	CONSTRAINT pk_devicetemplates PRIMARY KEY (devicetemplateid)
);

-- Create devices table
CREATE TABLE "VtDevice".devices (
	deviceid int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	devicename text NOT NULL,
	devicetemplateid int4 NOT NULL,
	claimingcode text NOT NULL,
	serialnumber text NULL,
	"uuid" text NULL,
	macaddress text NULL,
	ipaddress text NULL,
	pcbversion text NULL,
	CONSTRAINT pk_devices PRIMARY KEY (deviceid)
);

-- Create connectors table
CREATE TABLE "VtDevice".connectors (
	connectorid int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	controllerid int4 NOT NULL,
	connectornumber int4 NOT NULL,
	connectortypeid int4 NOT NULL,
	CONSTRAINT pk_connectors PRIMARY KEY (connectorid)
);

-- Create pins table
CREATE TABLE "VtDevice".pins (
	pinid int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	connectorid int4 NOT NULL,
	"position" int4 NOT NULL,
	deviceid int4 NOT NULL,
	CONSTRAINT pk_pins PRIMARY KEY (pinid)
);

-- Create datapointicons table
CREATE TABLE "VtDevice".datapointicons (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"label" text NOT NULL,
	"content" text NOT NULL,
	CONSTRAINT pk_datapointicons PRIMARY KEY (id)
);

-- Create datapoints table
CREATE TABLE "VtDevice".datapoints (
	datapointid int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	devicetemplateid int4 NOT NULL,
	"label" text NOT NULL,
	realtimechart text NOT NULL,
	"offset" int4 NOT NULL,
	length int4 NOT NULL,
	prepend text NOT NULL,
	historicalchart text DEFAULT ''::text NOT NULL,
	dataencoding text DEFAULT ''::text NOT NULL,
	append text DEFAULT ''::text NOT NULL,
	dataformat int4 DEFAULT 0 NOT NULL,
	decimals int4 DEFAULT 0 NOT NULL,
	wholenumber int4 DEFAULT 0 NOT NULL,
	datapointiconid int4 DEFAULT 0 NOT NULL,
	CONSTRAINT pk_datapoints PRIMARY KEY (datapointid)
);

-- Insert sample data to match the simulation and processing logic
-- Device Templates
INSERT INTO "VtDevice".devicetemplates (name, model, description, devicetypeid) VALUES 
('Environmental Sensor', 'ENV-S1', 'Environmental Sensor for Temp, Humidity, and CO2', 2),
('Power Monitor', 'PM-100', 'Power Monitoring Unit for Voltage and Current', 3);

-- Devices (Controllers and Sensors)
-- Controllers (MAC addresses without f2- prefix for database storage)
INSERT INTO "VtDevice".devices (devicename, devicetemplateid, claimingcode, macaddress) VALUES 
('F2 Controller 1', 1, 'claim-abc', 'aabbccddee01'),
('F2 Controller 2', 1, 'claim-def', 'aabbccddee02'),
('F2 Controller 3', 1, 'claim-ghi', 'aabbccddee03'),
('F2 Controller 4', 1, 'claim-jkl', 'aabbccddee04');

-- Sensors
INSERT INTO "VtDevice".devices (devicename, devicetemplateid, claimingcode) VALUES 
('Living Room Env Sensor', 2, 'claim-env1'),
('Kitchen Power Monitor', 3, 'claim-pm1'),
('Bedroom Env Sensor', 2, 'claim-env2');

-- Connectors for the Controllers (J1-J4 for each controller)
INSERT INTO "VtDevice".connectors (controllerid, connectornumber, connectortypeid) VALUES 
-- Controller 1 connectors
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee01'), 1, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee01'), 2, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee01'), 3, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee01'), 4, 3),
-- Controller 2 connectors
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee02'), 1, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee02'), 2, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee02'), 3, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee02'), 4, 3),
-- Controller 3 connectors
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee03'), 1, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee03'), 2, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee03'), 3, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee03'), 4, 3),
-- Controller 4 connectors
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee04'), 1, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee04'), 2, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee04'), 3, 3),
((SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee04'), 4, 3);

-- Pins: mapping sensors to controller connectors
INSERT INTO "VtDevice".pins (connectorid, position, deviceid) VALUES 
-- Controller 1, Connector 1, Pin 1 -> Living Room Env Sensor
((SELECT connectorid FROM "VtDevice".connectors WHERE controllerid = (SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee01') AND connectornumber = 1), 1, (SELECT deviceid FROM "VtDevice".devices WHERE devicename = 'Living Room Env Sensor')),
-- Controller 2, Connector 2, Pin 2 -> Kitchen Power Monitor
((SELECT connectorid FROM "VtDevice".connectors WHERE controllerid = (SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee02') AND connectornumber = 2), 2, (SELECT deviceid FROM "VtDevice".devices WHERE devicename = 'Kitchen Power Monitor')),
-- Controller 3, Connector 4, Pin 3 -> Bedroom Env Sensor
((SELECT connectorid FROM "VtDevice".connectors WHERE controllerid = (SELECT deviceid FROM "VtDevice".devices WHERE macaddress = 'aabbccddee03') AND connectornumber = 4), 3, (SELECT deviceid FROM "VtDevice".devices WHERE devicename = 'Bedroom Env Sensor'));

-- Data Points for the Sensor Templates
-- Environmental Sensor
INSERT INTO "VtDevice".datapoints (devicetemplateid, "label", datapointiconid, dataformat, dataencoding, "offset", length, decimals, prepend, append, realtimechart, historicalchart) VALUES
((SELECT devicetemplateid FROM "VtDevice".devicetemplates WHERE name = 'Environmental Sensor'), 'Temperature', 10, 0, 'Int16', 6, 2, 2, '', ' °C', 'gauge', 'line'),
((SELECT devicetemplateid FROM "VtDevice".devicetemplates WHERE name = 'Environmental Sensor'), 'Humidity', 5, 0, 'Uint16', 8, 2, 2, '', ' %', 'gauge', 'line'),
((SELECT devicetemplateid FROM "VtDevice".devicetemplates WHERE name = 'Environmental Sensor'), 'CO2', 3, 0, 'Uint16', 10, 2, 0, '',  ' ppm', 'gauge', 'line');

-- Power Monitor
INSERT INTO "VtDevice".datapoints (devicetemplateid, "label", datapointiconid, dataformat, dataencoding, "offset", length, decimals, prepend, append, realtimechart, historicalchart) VALUES
((SELECT devicetemplateid FROM "VtDevice".devicetemplates WHERE name = 'Power Monitor'), 'Voltage', 2, 0, 'Uint16', 0, 2, 1, '',  ' V',  'gauge', 'line'),
((SELECT devicetemplateid FROM "VtDevice".devicetemplates WHERE name = 'Power Monitor'), 'Current', 2, 0, 'Int16', 2, 2, 3,'',  ' A',  'gauge', 'line');

